### ISSUE TITLE
Support other implementations of time

### ISSUE THREAD

**Issue by nmathewson** [maybenot-io/maybenot#24]
Right now, maybenot only supports `std::time::Instant` and `std::time::Duration`.  But on some platforms, these types require a system call, which can be a bit expensive if we're doing a great many operations.  In arti, we're using [`coarsetime`](https://docs.rs/coarsetime/latest/coarsetime/) to avoid these syscalls when we can.

It would be quite convenient if maybenot could be parameterized to use a different implementation of time in its APIs.  I'd imagine that there would be some trait that would be implemented both by `coarsetime` and `sys::time`, and that framework would be parameterized on this trait (with default usage of std::time).  But other implementations are probably possible too.

**Comment by pylls** [comment]
@faern , do you maybe have any input on how to best make this happen cleanly for v2? Time is isolated to `framework.rs` and `action.rs` (`TriggerAction` lives there) and is mostly an interface issue for the integrator.  Internally, the framework operates on sampled microseconds turned into `Duration` and simple comparisons of provided time.

**Comment by faern** [comment]
@nmathewson Do you have any measurements on how much performance difference `std` time vs `coarsetime` makes for you? Or any comparison in general? I don't see any solid data in the docs or repo for `coarsetime`. It just vaguely says it might be faster than the standard library.

We can make the time source configurable, and it would probably not be too complex. However, it would add API complexity, and I have not really seen other projects being parameterized over this. Do you have examples of other Rust projects having pluggable time sources?

**Comment by nmathewson** [comment]
> @nmathewson Do you have any measurements on how much performance difference std time vs coarsetime makes for you? Or any comparison in general? I don't see any solid data in the docs or repo for coarsetime. It just vaguely says it might be faster than the standard library.

Sure; I just did some benchmarks.  On my desktop, `coarsetime::Instant::now()` is about 3-4x as fast as `std::time::Instant::now()`.  In context of Tor, the savings is about 9% of the total time needed to encrypt a single layer of a Tor cell. 

I've reproduced this on MacOS and Linux, both on fairly high-end hardware.  I'm afraid I don't have lower-end hardware or a windows installation to test with.  I seem to recall that the performance difference between the two implementations `Instant::now()` is higher on low-end machines and on windows.  I don't know whether the increased cost of AES on those systems overwhelms the performance difference.

>Do you have examples of other Rust projects having pluggable time sources?

Two examples I found early on are:
  * `libsw`: https://docs.rs/libsw/3.3.1/libsw/
  * `governor`: https://docs.rs/governor/latest/governor/clock/index.html

(There are some others, like `moka`, where you can adjust which time source is used based on a feature, but those only support one time source per build configuration.)

**Comment by faern** [comment]
Interesting! 9%, that's a significant chunk of the entire time. With that number I do feel we could make the time source configurable. We did make the PRNG source configurable for a similar reason, so why not.

I have not read about `coarsetime` yet. Do we need to accept an *instance* of some object to properly use it, or is it fine to just call the associated constructor method `Instant::now()`? That method seems to update the underlying time, so I'm surprised it's so much faster. But anyway. If we don't need an instance, we don't need to take any new argument, we just need a generic parameter telling the framework what time functions to call into.

**Comment by nmathewson** [comment]
>Do we need to accept an instance of some object to properly use it, or is it fine to just call the associated constructor method Instant::now()?

For our case, we just need two things:
  * Use of the associated constructor `coarsetime::Instant::now()`
  * Use of the `coarsetime::Duration` type whenever possible

Ideally, this would be done by providing a set of traits that `coarsetime::Instant` and `coarsetime::Duration` could implement.

>That method seems to update the underlying time, so I'm surprised it's so much faster.

This is a confusing aspect of coarsetime: it actually speeds up the time lookup in two ways.
   1. If you use `coarsetime::Instant::now()`, it uses a system API that is faster but less precise than the one used by `std::Instant::now()`.  (For example, on Linux, instead of CLOCK_MONOTONIC, it uses CLOCK_MONOTONIC_COARSE.) That's where we get the benefit in our case.
   2. It also caches the most recent time, so that you can get it via `coarsetime::Instant::recent().`  Arti doesn't use that feature.

**Comment by faern** [comment]
I finally got around to test this out. Turns it it was fairly simple to be generic over time. Please try out the code and come with feedback on the solution proposed in #27

**Comment by pylls** [comment]
This was solved in #27 , and documented important limitations [in a later commit](https://github.com/maybenot-io/maybenot/commit/106d74630df2606b081338bd6cf70a1dc71706e9) as part of the `v2` branch. Thanks again @faern and @nmathewson !
